#!/bin/bash

brightness=/sys/class/backlight/intel_backlight/brightness
max_brightness=/sys/class/backlight/intel_backlight/max_brightness

cur=$(cat $brightness)
max=$(cat $max_brightness)
min=1

new=$(($cur $1 $2))
new=$(($new>$max?$max:$new))
new=$(($new<$min?$min:$new))

echo "echo $new > $brightness" | sudo bash

